<?php
$now = time();
$dayofmonth = date('d', $now);
$dayofweektext = date('D', $now);
$dayofmonthwithoutleadingzeros = date('j', $now);
$dayofweekfullword = date('l', $now);
$iso8601 = date('N', $now);
$dayofmonthsuffix = date('S', $now);
$dayofweeknumber = date('w', $now);
$dayofyear = date('z', $now);
$weekofyear = date('W', $now);
$fullmonth = date('F', $now);
$monthnumber = date('m', $now);
$shortmonth = date('M', $now);
$monthnumberwithoutleadingzeroes = date('n', $now);
$daysinmonth = date('t', $now);
$leapyear = date('L', $now);
$iso8601weekyear = date('o', $now);
$fullyear = date('X', $now);
$fullyear10000 = date('x', $now);
$fullyear4digitsminus = date('Y', $now);
$twodigityear = date('y', $now);
$ampmlowercase = date('a', $now);
$ampmuppercase = date('A', $now);
$swatchinternettime = date('B', $now);
$hour12withoutleadingzeros = date('g', $now);
$hour24withoutleadingzeros = date('G', $now);
$hour12 = date('h', $now);
$hour24 = date('H', $now);
$minute = date('i', $now);
$second = date('s', $now);
$microsecond = date('u', $now);
$millisecond = date('v', $now);
$timezoneid = date('e', $now);
$isdst = date('I', $now);
$gmtdifference = date('O', $now);
$gmtdifferencewithcolon = date('P', $now);
$gmtdifferencewithz = date('p', $now);
$timezoneabbreviation = date('T', $now);
$timezoneoffsetseconds = date('Z', $now);
$iso8601date = date('c', $now);
$rfc2822rfc5322 = date('r', $now);
$unix1970seconds = date('U', $now);
echo 'Current day of month: '.$dayofmonth.'<br>';
echo 'Current day of week: '.$dayofweektext.'('.$dayofweekfullword.')<br>';
echo 'Current day of week in ISO 8601 notation '.$iso8601.'<br>';
echo 'Current day of month in English ordinal suffix: '.$dayofmonthsuffix.'<br>';
echo 'Current day of week in numeric representation: '.$dayofweeknumber.'<br>';
echo 'Current day of year: '.$dayofyear.'<br>';
echo 'Current ISO 8601 week of year: '.$weekofyear.'<br>';
echo 'Current month: '.$monthnumber.'('.$shortmonth.') ('.$fullmonth.')<br>';
echo 'Number of days in current month: '.$daysinmonth.'<br>';
echo 'Is the current year a leap Year? '.$leapyear.'<br>';
echo 'Current year in ISO 8601 format: '.$iso8601weekyear.'<br>';
echo 'Current year: '.$fullyear.'<br>';
echo 'Current two digit year: '.$twodigityear.'<br>';
echo 'Current am/pm: '.$ampmlowercase.'<br>';
echo 'Current swatch Internet time '.$swatchinternettime.'<br>';
echo 'Current hour in 12 hour format: '.$hour12withoutleadingzeros.'<br>';
echo 'Current hour in 24 hour format: '.$hour24withoutleadingzeros.'<br>';
echo 'Current minute: '.$minute.'<br>';
echo 'Current second: '.$second.'<br>';
echo 'Current microsecond: '.$microsecond.'<br>';
echo 'Current millisecond: '.$millisecond.'<br>';
echo 'Current timezone identifier: '.$timezoneid.'<br>';
echo 'Is the current time in daylight saving time? '.$isdst.'<br>';
echo 'Current time zone difference: '.$gmtdifferencewithcolon.'<br>';
echo 'Current time zone abbreviation: '.$timezoneabbreviation.'<br>';
echo 'Current time zone offest in seconds: '.$timezoneoffsetseconds.'<br>';
echo 'Current ISO 8601 date: '.$iso8601date.'<br>';
echo 'Current RFC 2822/5322 formatted date: '.$rfc2822rfc5322.'<br>';
echo 'Current seconds since unix epoch (January 1 1970): '.$unix1970seconds.'<br>';
?>